### ISSUE TITLE
Mnemonic functions instead of structs

### ISSUE THREAD

**Issue by tekknolagi** [grassator/mass#46]
Neat project! Perusing the source and had some thoughts -- take 'em or leave 'em :)

The following is a bit of a mouthful:

```c
    push_eagerly_encoded_assembly(
      &builder.code_block, source_range,
      &(Instruction_Assembly){call, {instance->storage}}
    );
```

and might be a little more readable as:

```c
call(&builder.code_block, source_range, instance->storage);
```

It might be possible to do this by defining a bunch of functions in the `mnemonic` macro in instructions.c but I am not sure how to handle multiple arities from function arguments -> struct members.

**Comment by grassator** [comment]
> Neat project!

Thanks!

> call(&builder.code_block, source_range, instance->storage);

I've thought about something like this as well, but there is an issue - many instructions support variable number of operands. In C language that would require either doing varargs with a null terminator or do some fancy tricks with non-standard macros. With former it is not going to be nice to use and with latter it is a bit of a nightmare to maintain.

So for now I decided that sticking with a more verbose form is OK.

Thanks for sharing your thoughts though - I appreciate any and all interest in the project!
