### ISSUE TITLE
Two questions or several?

### ISSUE THREAD

**Issue by Spoiledpay** [grassator/mass#71]
Great work!!!
About Mass. Where will we have some additional examples for console and Windows GUI?

Could we have grammar or reserved words to be able to delve deeper into creating programs for Windows?

And some small native Windows Window (GUI) example, a HelloWorld.

Thanks.

**Comment by grassator** [comment]
Hello, thank you for reaching out, however Mass is still very much in a research phase so I would advise heavily against trying to use it for anything besides playing around. There are big changes coming, for example it is likely that overloading in the current will be replace by an interface/trait system.
